### ISSUE TITLE
Master changes not in 1.0 release

### ISSUE THREAD

**Issue by roblewisink** [grimmlink/TimingField#2]
Not sure this is still being developed, but I found it helpful and just wanted to note that the updates in the master, specifically the "trigger event" is not in the 1.0 repository and thus doesn't get installed via composer.  

Additionally I found it helpful to add the "Input" trigger to the updateElem() function in order for Angular to see the changes.
`        updateElem: function() {`
           ` this.elem.val(this.hmsToTimestamp(`
               ` this.getHours().value,`
              ` this.getMinutes().value,`
               ` this.getSeconds().value`
          `  )).trigger( "change" ).trigger( "input" );  // Added input trigger for Angular listener. `
       ` },`

**Comment by grimmlink** [comment]
Fixed in https://github.com/grimmlink/TimingField/commit/6035be0bb80fd7dbe8fd5b7ed416b35178a07c7a
