### ISSUE TITLE
Intervals are not working

### ISSUE THREAD

**Issue by FANMixco** [grimmlink/TimingField#3]
Hi Guillaume,

I think your plugin is really awesome! However, I have finished in a small constrain regarding this part of the code:
`            this.tpl.find('.timingfield_hours .timingfield_next')
                .on('mouseup', function() { clearInterval(timeoutId); return false; })
                .on('mousedown', function(e) { timeoutId = setInterval($.proxy(this.upHour, this), 100); return false;  })
            ;
`

This part is fully ignored. Do you know what should be changed in order to allow the interval to work? Thanks for your ideas.

**Comment by grimmlink** [comment]
Hi,

Thanks, I developped this plugin for my projects.
This interval is actually useless as its overriden just a few lines below.
I removed it in https://github.com/grimmlink/TimingField/commit/50c0ab81bf1d8f9a637977cbb7e42f2016a2f08c

All updates are in 1.1
